<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.547">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Gazze - Landa - Irisarri">

<title>Trabajo Práctico 1: The Multiarmed Bandit</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="informe_files/libs/clipboard/clipboard.min.js"></script>
<script src="informe_files/libs/quarto-html/quarto.js"></script>
<script src="informe_files/libs/quarto-html/popper.min.js"></script>
<script src="informe_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="informe_files/libs/quarto-html/anchor.min.js"></script>
<link href="informe_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="informe_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="informe_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="informe_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="informe_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="informe_files/libs/kePrint-0.0.1/kePrint.js"></script>
<link href="informe_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Contenido</h2>
   
  <ul>
  <li><a href="#introducción" id="toc-introducción" class="nav-link active" data-scroll-target="#introducción">Introducción:</a></li>
  <li><a href="#objetivos" id="toc-objetivos" class="nav-link" data-scroll-target="#objetivos">Objetivos:</a></li>
  <li><a href="#desarrollo" id="toc-desarrollo" class="nav-link" data-scroll-target="#desarrollo">Desarrollo</a>
  <ul class="collapse">
  <li><a href="#jugador-privilegiado" id="toc-jugador-privilegiado" class="nav-link" data-scroll-target="#jugador-privilegiado"><em>Jugador privilegiado</em></a></li>
  <li><a href="#estrategia-1-completamente-al-azar" id="toc-estrategia-1-completamente-al-azar" class="nav-link" data-scroll-target="#estrategia-1-completamente-al-azar"><em>Estrategia 1: Completamente al azar</em></a></li>
  <li><a href="#estrategia-2-greedy-con-tasa-observada" id="toc-estrategia-2-greedy-con-tasa-observada" class="nav-link" data-scroll-target="#estrategia-2-greedy-con-tasa-observada"><em>Estrategia 2: Greedy con tasa observada</em></a></li>
  <li><a href="#estrategia-3-greedy-con-probabilidad-a-posteriori" id="toc-estrategia-3-greedy-con-probabilidad-a-posteriori" class="nav-link" data-scroll-target="#estrategia-3-greedy-con-probabilidad-a-posteriori"><em>Estrategia 3: Greedy con probabilidad a posteriori</em></a></li>
  <li><a href="#estrategia-4-epsilon--greedy-con-tasa-observada" id="toc-estrategia-4-epsilon--greedy-con-tasa-observada" class="nav-link" data-scroll-target="#estrategia-4-epsilon--greedy-con-tasa-observada"><em>Estrategia 4: <span class="math inline">\(\epsilon\)</span> -greedy (con tasa observada)</em></a></li>
  <li><a href="#estrategia-5-softmax" id="toc-estrategia-5-softmax" class="nav-link" data-scroll-target="#estrategia-5-softmax"><em>Estrategia 5: Softmax</em></a></li>
  <li><a href="#estrategia-6-upper-bound" id="toc-estrategia-6-upper-bound" class="nav-link" data-scroll-target="#estrategia-6-upper-bound"><em>Estrategia 6: Upper-bound</em></a></li>
  <li><a href="#estrategia-7-thompson-sampling" id="toc-estrategia-7-thompson-sampling" class="nav-link" data-scroll-target="#estrategia-7-thompson-sampling"><em>Estrategia 7: Thompson sampling</em></a></li>
  </ul></li>
  <li><a href="#conclusiones" id="toc-conclusiones" class="nav-link" data-scroll-target="#conclusiones">Conclusiones</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Trabajo Práctico 1: The Multiarmed Bandit</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Gazze - Landa - Irisarri </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="introducción" class="level1">
<h1>Introducción:</h1>
<p>Se presenta el problema del tipo “<em>multi-armed bandit”, en el cual se desea elegir entre tres máquinas tragamonedas, con el propósito de maximizar las ganancias.</em> El juego de las maquinitas consiste en hacer girar sus rodillos (analógicos o digitales) con el objetivo de obtener una combinación de símbolos ganadora y así acceder a un premio monetario.</p>
<p>Cada máquina tiene una probabilidad de éxito desconocida y potencialmente diferente, es decir, una probabilidad distinta de entregar un premio. Este es un desafío que enfrenta a los jugadores con la decisión de explotar lo conocido o explorar lo desconocido para maximizar sus ganancias, donde la información es clave pero limitada: cada tirada de una máquina revela un poco más sobre su rendimiento, pero también podría cambiar tu percepción sobre cuál es la mejor opción.</p>
<p>En la fase inicial, cuando se sabe poco sobre las máquinas, podría ser más prudente <em>“explorar”</em>, probando cada máquina varias veces para obtener una estimación aproximada de sus probabilidades de éxito. A medida que se acumulan datos sobre el rendimiento de cada máquina, la estrategia podría cambiar a <em>“explotar”</em> la máquina que ha demostrado ser la más rentable. Sin embargo, siempre existe la incertidumbre y la posibilidad de que una de las máquinas menos utilizadas tenga en realidad una tasa de éxito mayor. Este problema se complica aún más por el hecho de que cada elección de máquina proporciona información que podría alterar nuestra comprensión de cuál es la mejor opción. La solución óptima a este problema involucra un equilibrio cuidadoso entre explorar para ganar información y explotar esa información para maximizar las ganancias.</p>
<p>En nuestro escenario, no hay costo para jugar, lo que significa que no pierdes nada al jugar con una máquina. Es decir, si obtenemos una combinación ganadora, sumamos una unidad monetaria, pero si no, no perdemos nada. En este estudio se realizará un año de experimentación continua (366 días), dedicando cada día a una sola máquina.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="adultos_jugando.jpg" class="img-fluid figure-img"></p>
<figcaption>Adultos mayores usufructuando las diferentes estrategias</figcaption>
</figure>
</div>
</section>
<section id="objetivos" class="level1">
<h1>Objetivos:</h1>
<p>El objetivo del trabajo consiste en evaluar y comparar diferentes estrategias de juego. Se analizarán mediante simulaciones diferentes planes de exploración y explotación de las máquinas para identificar cuál de estos proporciona la mayor ganancia esperada.</p>
<p>Para el estudio mediante simulaciones, consideraremos que las probabilidades de éxito de las tres máquinas son <span class="math inline">\(\theta_a = 0.30\)</span>, <span class="math inline">\(\theta_b = 0.55\)</span> y <span class="math inline">\(\theta_c = 0.45\)</span>. Recordemos que estas probabilidades son desconocidas (no podemos basar nuestras estrategias en esos valores, sino en las estimaciones que vamos haciendo de ellos).</p>
</section>
<section id="desarrollo" class="level1">
<h1>Desarrollo</h1>
<p>A continuación se presenta el análisis de las siete estrategias estudiadas. Para todas ellas, se parte de una ditribución a priori de la probabilidad de éxito de cada máquina Beta(2, 2).</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="informe_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="jugador-privilegiado" class="level2">
<h2 class="anchored" data-anchor-id="jugador-privilegiado"><em>Jugador privilegiado</em></h2>
<p>Antes de comenzar con la exposición de las estrategias, se simula los resultados de un jugador con información privilegiada y juega 366 días con la mejor máquina</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: black !important; background-color: lightblue !important;"></th>
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: black !important; background-color: lightblue !important;">Medidas resumen</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">Min. :170.0</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">1st Qu.:194.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">Median :201.0</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">Mean :200.6</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">3rd Qu.:207.0</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">Max. :229.0</td>
</tr>
</tbody>
</table>


</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="informe_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Sin dudas esta es la mejor situación posible, se visualiza una ganacia anual con una distribución que luce normal, centrada en 200 unidades monetarias, pero recordemos, realmente no se conoce cuál es la mejor máquina, asi que, a explorar y/o explotar…</p>
</section>
<section id="estrategia-1-completamente-al-azar" class="level2">
<h2 class="anchored" data-anchor-id="estrategia-1-completamente-al-azar"><em>Estrategia 1: Completamente al azar</em></h2>
<p>En esta estrategia cada día se juega con una máquina seleccionada al azar con igual probabilidad. Se podria decir que esta es una estrategia de exploración constante.</p>
<p>Se presenta la función creada para simular la elección de una máquina y su respectiva tirada. A esta se le envia una lista con los parámetros necesarios como <span class="math inline">\(\theta\)</span> o probabilidad de éxito real de cada máquina, <span class="math inline">\(\alpha\)</span> y <span class="math inline">\(\beta\)</span> parámetros de las distribuciones a priori, etc. La función decide, como bien indica su nombre, una de las tres máquinas de manera al azar y simula la jugada con esa máquina. Luego nos devuelve los valores actualizados de los parámetros.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>al_azar <span class="ot">&lt;-</span> <span class="cf">function</span>(lista1) {</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  alphas <span class="ot">&lt;-</span> lista1[[<span class="dv">1</span>]]</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  betas <span class="ot">&lt;-</span> lista1[[<span class="dv">2</span>]]</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  tethas <span class="ot">&lt;-</span> lista1[[<span class="dv">3</span>]]</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  prior_df <span class="ot">&lt;-</span> lista1[[<span class="dv">4</span>]]</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  x1<span class="ot">=</span><span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="at">length.out =</span><span class="dv">200</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  sample <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(alphas), <span class="dv">1</span>)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>  juego <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(<span class="dv">1</span>, <span class="dv">1</span>, tethas[sample])</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>  alphas[sample] <span class="ot">&lt;-</span> alphas[sample] <span class="sc">+</span> juego</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>  betas[sample] <span class="ot">&lt;-</span> betas[sample] <span class="sc">+</span> <span class="dv">1</span> <span class="sc">-</span> juego</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>  postirior <span class="ot">&lt;-</span> <span class="fu">dbeta</span>(x1, alphas[sample],  betas[sample])</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>  prior_df[, sample] <span class="ot">&lt;-</span> postirior</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>  salida1_list <span class="ot">&lt;-</span> <span class="fu">list</span>(alphas, betas, tethas, prior_df, sample, juego)</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(salida1_list)</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Luego, se utiliza esta función para simular las jugadas diarias durante un año. A partir de esta información se registró la evolución diaria del dinero acumulado cada día, la cantidad de veces que se jugó con cada máquina y la distribución a posteriori de la probabilidad de éxito para cada máquina.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="informe_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="informe_files/figure-html/unnamed-chunk-5-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="informe_files/figure-html/unnamed-chunk-5-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Se observa que las distribuciones a posteriori de las probabilidades de éxito de cada máquina se van centrando en el verdadero valor del parámetro a medida que aumenta la cantidad de días jugados. Esto es una situación que se repetirá en todas las estrategias, por lo cual solo se presentará el gráfico de las distribuciones a posteriori finales de aquí en adelante.<br>
En el gráfico de barras se observa que se jugó de manera parecida con las tres máquinas esto se debe a que la elección de las mismas se realiza de manera aleatoria, sin tener en cuenta lo ocurrido anteriormente. Puede observarse que la máquina 2 es la que proporciona un mayor cantidad de éxitos, mientras que la 1 parece ser la peor. Luego de un año de simulaciones, se obtuvo una ganancia de 159 unidades monetarias.</p>
<p>El mismo procedimiento realizado para un año se repite por un período de 1000 años. A continuación se presentan los resultados.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="informe_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "La ganancia media por año es  159.33 unidades monetarias"</code></pre>
</div>
</div>
<p>A traves de la simulación de los 1000 años, se observa la distribución de las ganancias, la cual presenta un comportamiente simétrico centrado en aproximadamente 160 unidades monetarias por año.</p>
<p>Por último se concluye que esta estrategia no podría considerarse bayesiana, ya que siempre elige la máquina a utilizar de manera aleatoria, sin tener en cuenta la información recolectada.</p>
</section>
<section id="estrategia-2-greedy-con-tasa-observada" class="level2">
<h2 class="anchored" data-anchor-id="estrategia-2-greedy-con-tasa-observada"><em>Estrategia 2: Greedy con tasa observada</em></h2>
<p>En esta estrategia se elige la máquina que tenga la mayor tasa de éxito observada hasta el momento. Esta tasa para cada máquina la calculamos como cantidad de días ganados sobre días jugados. Partiendo de una creencia inicial de que las tasas de éxito para las tres máquinas son iguales a 0.5. Con esta técnia se corre el riesgo de perder la primera vez que se juega con una máquina, su tasa se actualice a cero y no volver a utilizarla. Para omitir estos casos realizamos 10 tiradas de calentamiento previamente.</p>
<p>Se presenta la función que replica esta estrategia para un día. A esta se le envia una lista con los parámetros necesarios. La función elige de manera aleatoria la máquina a utilizar si el día simulado se encuentra entre los primeros 10, en los restantes elige la que presenta mayor tasa de éxito, simula la jugada y luego nos devuelve los valores actualizados de los parámetros.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>greedy_tasa_obs<span class="ot">&lt;-</span><span class="cf">function</span>(lista2){</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  fl_calentamiento <span class="ot">&lt;-</span> lista2[[<span class="dv">5</span>]]</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  t <span class="ot">&lt;-</span> lista2[[<span class="dv">2</span>]]</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  tethas <span class="ot">&lt;-</span> lista2[[<span class="dv">1</span>]]</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (fl_calentamiento){</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>    sample <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, <span class="dv">1</span>)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>  <span class="cf">else</span>{</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>    sample <span class="ot">&lt;-</span> <span class="fu">order</span>(t <span class="sc">+</span> <span class="fu">runif</span>(<span class="dv">3</span>,<span class="fl">0.001</span>, <span class="fl">0.009</span>), <span class="at">decreasing =</span> <span class="cn">TRUE</span>)[<span class="dv">1</span>]</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>  juego <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(<span class="dv">1</span>, <span class="dv">1</span>, tethas[sample])</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>  lista2_salida<span class="ot">&lt;-</span><span class="fu">list</span>(tethas, t, juego, sample, fl_calentamineto)</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(lista2_salida)</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Aplicando este procedimiento para simular cada día jugado del año obtenemos:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="informe_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="informe_files/figure-html/unnamed-chunk-8-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="informe_files/figure-html/unnamed-chunk-8-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "La ganancia de este año es  202 unidades monetarias"</code></pre>
</div>
</div>
<p>Se observa que este método en el año simulado elige mayormente la máquina 2, esto se debe a que presentó una mayor tasa de éxitos y se mantuvo constante durante este tiempo. En el gráfico de las distribuciones a posteriori se ve que la más modificada es la correspondiente a la máquina dos, debido a que ésta fue la más utilizada. Además se nota que se concentra alrededor del verdadero valor poblacional (<span class="math inline">\(\theta_2 = 0.55\)</span>). Se presenta un tercer gráfico con la evolución de las ganancias acumuladas durante el año.</p>
<p>Luego se repite este procedimiento para simular 1000 años jugados con esta estrategia y se analizan los resultados.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="informe_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "La ganancia media por año es  185.585 unidades monetarias"</code></pre>
</div>
</div>
<p>Se grafica la distribución aproximada de la ganancia anual. En este se diferencian tres modas, estas corresponden a la cantidad de años en los cuales se usaron mayormente las máquinas uno, tres y dos respectivamente. La media de las ganancias anuales es 185.8 unidades monetarias. Además se puede notar que mayormente se obtuvieron ganancias altas, por lo que suponemos que se utilizó en mayor medida la máquina dos.</p>
<p>El método utilizado para la elección de la máquina no es bayesiano, ya que, no se utiliza información de la distribución a posteriori, solo se tiene en cuenta el valor de las tasas de éxito observadas hasta el momento.</p>
</section>
<section id="estrategia-3-greedy-con-probabilidad-a-posteriori" class="level2">
<h2 class="anchored" data-anchor-id="estrategia-3-greedy-con-probabilidad-a-posteriori"><em>Estrategia 3: Greedy con probabilidad a posteriori</em></h2>
<p>En esta estrategia se elige la máquina que tenga, hasta el momento, mayor probabilidad de éxito promedio a posteriori.</p>
<p>Se presenta la función que simula esta estrategia para un día.Para esto se calculan las esperanzas de las tres distribuciones a priori y se utiliza la máquina que presenta el mayor valor. Luego se simula el juego con la máquina elegida y se actualizan las distribuciones.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>greedy_prob_posterior<span class="ot">&lt;-</span><span class="cf">function</span>(lista3){</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  tethas <span class="ot">&lt;-</span> lista3[[<span class="dv">1</span>]]</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  alphas <span class="ot">&lt;-</span> lista3[[<span class="dv">2</span>]]</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  betas <span class="ot">&lt;-</span> lista3[[<span class="dv">3</span>]]</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>  esperanzas <span class="ot">=</span> <span class="fu">c</span>(alphas[<span class="dv">1</span>]<span class="sc">/</span>(alphas[<span class="dv">1</span>]<span class="sc">+</span>betas[<span class="dv">1</span>]),</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>                alphas[<span class="dv">2</span>]<span class="sc">/</span>(alphas[<span class="dv">2</span>]<span class="sc">+</span>betas[<span class="dv">2</span>]),</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>                alphas[<span class="dv">3</span>]<span class="sc">/</span>(alphas[<span class="dv">3</span>]<span class="sc">+</span>betas[<span class="dv">3</span>]))</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>  <span class="co">#print(esperanzas)</span></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>  sample <span class="ot">&lt;-</span> <span class="fu">order</span>(esperanzas <span class="sc">+</span> <span class="fu">runif</span>(<span class="dv">3</span>,<span class="fl">0.001</span>, <span class="fl">0.009</span>)  , <span class="at">decreasing =</span> <span class="cn">TRUE</span>)[<span class="dv">1</span>]</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>  juego <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(<span class="dv">1</span>, <span class="dv">1</span>, tethas[sample])</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>  alphas[sample] <span class="ot">&lt;-</span> alphas[sample] <span class="sc">+</span> juego</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>  betas[sample] <span class="ot">&lt;-</span> betas[sample] <span class="sc">+</span> <span class="dv">1</span> <span class="sc">-</span> juego</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>  lista3_salida<span class="ot">&lt;-</span><span class="fu">list</span>(tethas, alphas, betas, juego, sample)</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(lista3_salida)</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Reiterando este método para simular las jugadas de un año se obtiene:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="informe_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="informe_files/figure-html/unnamed-chunk-11-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="informe_files/figure-html/unnamed-chunk-11-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "La ganancia de este año es  202 unidades monetarias"</code></pre>
</div>
</div>
<p>Se observa que la máquina más utilizada es la número dos presentando la mayor esperanza en su distribucion a posteriori. Viendo las distribuciones a posteriori se puede notar que los valores de la máquina dos está más concentrada alrededor de 0.55. Mientras que para las máquinas uno y tres la dispersión de los valores es mayor, esto se debe a que estas máquinas fueron las menos utilizadas. Con el último gráfico se observa la evolución de las ganancias a traves del paso de los días, obteniendo una ganancia total de 202 unidades monetarias.</p>
<p>Luego se repite este procedimiento para simular 1000 años jugados con esta estrategia y se analizan los resultados.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="informe_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "La ganancia media por año es  189.178 unidades monetarias"</code></pre>
</div>
</div>
<p>Luego de simular 1000 años, se grafican las ganancias anuales y se observa una distribución bimodal con modas aproximadamente en 160 y 190 unidades monetarias, correspondientes a las maquinas dos y tres respectivamente. La ganancia media para los 1000 años de simulación resulta igual a 189.17 unidades monetarias. El método es bayesiano ya que utiliza la máquina con probabilidad de éxito promedio más alta, es decir, la que presenta mayor esperanza en su distribución a posteriori y estas se actualizan en base a los resultados obtenidos tirada tras tirada</p>
</section>
<section id="estrategia-4-epsilon--greedy-con-tasa-observada" class="level2">
<h2 class="anchored" data-anchor-id="estrategia-4-epsilon--greedy-con-tasa-observada"><em>Estrategia 4: <span class="math inline">\(\epsilon\)</span> -greedy (con tasa observada)</em></h2>
<p>Se selecciona la mejor máquina (la de mayor tasa de éxito observada según los datos actuales) con una probabilidad de <span class="math inline">\(\epsilon\)</span> y se elige una máquina al azar con una probabilidad <span class="math inline">\(1-\epsilon\)</span>. En este contexto, <span class="math inline">\(\epsilon\)</span> es una constante que varía entre 0 y 1, y su valor determina la proporción de tiempo que el jugador dedicará a la exploración en comparación con la explotación.</p>
<p>Se presenta la función que simula esta estrategia para un día.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>e_greedy_tasa_obs<span class="ot">&lt;-</span><span class="cf">function</span>(lista4){</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  e<span class="ot">&lt;-</span>lista4[[<span class="dv">3</span>]]</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  explote<span class="ot">&lt;-</span><span class="fu">runif</span>(<span class="dv">1</span>)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  lista4[[<span class="dv">6</span>]] <span class="ot">=</span> <span class="dv">0</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  lista4[[<span class="dv">7</span>]] <span class="ot">=</span> <span class="dv">0</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>(explote<span class="sc">&lt;=</span><span class="dv">1</span><span class="sc">-</span>e){<span class="co">#Elige el mejor</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>    lista4[[<span class="dv">7</span>]] <span class="ot">=</span> <span class="dv">1</span> <span class="co"># exploto</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>    sample <span class="ot">&lt;-</span>  <span class="fu">order</span>(t <span class="sc">+</span> <span class="fu">runif</span>(<span class="dv">3</span>,<span class="fl">0.001</span>, <span class="fl">0.009</span>), <span class="at">decreasing =</span> <span class="cn">TRUE</span>)[<span class="dv">1</span>]</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>  }<span class="cf">else</span>{<span class="co">#Elige aleatoriamente </span></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>    lista4[[<span class="dv">6</span>]] <span class="ot">=</span> <span class="dv">1</span> <span class="co"># exploro</span></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>    sample <span class="ot">&lt;-</span>  <span class="fu">as.numeric</span>(<span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, <span class="dv">1</span>))</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>  juego <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(<span class="dv">1</span>, <span class="dv">1</span>, tethas[sample])</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>  lista4_salida<span class="ot">&lt;-</span><span class="fu">list</span>(tethas, t, e, juego, sample, lista4[[<span class="dv">6</span>]], lista4[[<span class="dv">7</span>]])</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(lista4_salida)</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Se elige un <span class="math inline">\(\epsilon=0.05\)</span>, esto significa que el jugador gastará el 5% de su tiempo explorando nuevas máquinas y el 95% restante explotando la máquina que ha demostrado ser más rentable hasta ese momento. Reiterando este método para simular las jugadas de un año se obtiene:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="informe_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="informe_files/figure-html/unnamed-chunk-14-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="informe_files/figure-html/unnamed-chunk-14-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "La ganancia de este año es  170 unidades monetarias"</code></pre>
</div>
</div>
<p>Se observa que se utilizan las 3 máquinas de manera similar,tambien se puede notar que las tiradas en la máquina 2 presentan una proporción de éxitos mayor en comparación a las 2 restantes. Viendo las distribuciones a posteriori se puede notar que al haberse realizado una cantidad de tiradas similiar en las 3 máquinas estas sus valores se encuentran concentrados alrededor del verdadero valor del parámetro (<span class="math inline">\(\theta_1\)</span>,<span class="math inline">\(\theta_2\)</span>,<span class="math inline">\(\theta_3\)</span>). Con el último gráfico se observa la evolución de las ganancias a traves del paso de los días, obteniendo una ganancia total de 170 unidades monetarias.</p>
<p>Luego se repite este procedimiento para simular 1000 años jugados con esta estrategia, a su vez, se varía el tiempo de exploración elegido (<span class="math inline">\(\epsilon = (0.05, 0.1, 0.2)\)</span> ) y se analizan los resultados.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "La ganancia media por año utilizando e =  0.05   es 158.092 unidades monetarias"
[1] "La ganancia media por año utilizando e =  0.2   es 158.545 unidades monetarias"
[1] "La ganancia media por año utilizando e =  0.4   es 158.742 unidades monetarias"</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="informe_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Luego de simular 1000 años, se grafican las ganancias anuales para los distintos valores de <span class="math inline">\(\epsilon\)</span>, a traves de los mismos vemos distribuciones parecidas, todas centradas en aproximadamente 160 unidades monetarias. La ganancia media para los 1000 años de simulación tomando <span class="math inline">\(\epsilon\)</span> igual a 0.05, 0.2 y 0.4 resultan 158.84, 158.76 y 158.34 unidades monetarias respectivamente. El método no es bayesiano ya que utiliza la máquina con tasa de éxito mayor con probabilidad <span class="math inline">\(1-\epsilon\)</span>, y elige una máquina de manera aleatoria con probabilidad <span class="math inline">\(\epsilon\)</span>, sin tener en cuenta las distribuciones a posteriori de cada máquina.</p>
</section>
<section id="estrategia-5-softmax" class="level2">
<h2 class="anchored" data-anchor-id="estrategia-5-softmax"><em>Estrategia 5: Softmax</em></h2>
<p>Dada la tasa observada para cada máquina i, <span class="math inline">\(\pi_i\)</span> se calcula una probabilidad de elegir cada máquina utilizando la función softmax: <span class="math display">\[Pr(i)=\frac{exp(\pi_i/\tau)}{\sum_{j=1}^{3}exp(\pi_i/\tau)}\]</span> donde <span class="math inline">\(\tau\)</span> es un parámetro de “temperatura” que controla el grado de exploración. Luego, se elige la máquina i con probabilidad <span class="math inline">\(Pr(i)\)</span> . Se presenta la función “softmax” que para ciertos valores de las tasas (<span class="math inline">\(\pi_i\)</span>) y el parámetro de temperatura (<span class="math inline">\(\tau\)</span>), nos devuelve la probabilidad de utilizar cada una de las máquinas; y la función que replica esta estrategia para un día. A esta se le envia una lista con los parámetros necesarios. La función elige una máquina con probabilidad <span class="math inline">\(Pr(i)\)</span> , simula la jugada y luego nos devuelve los valores actualizados de los parámetros.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Función softmax</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>softmax<span class="ot">=</span> <span class="cf">function</span>(tau,pi){</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  pr_soft1 <span class="ot">=</span> <span class="fu">exp</span>(pi[<span class="dv">1</span>]<span class="sc">/</span>tau)<span class="sc">/</span><span class="fu">sum</span>(<span class="fu">exp</span>(pi<span class="sc">/</span>tau))</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  pr_soft2 <span class="ot">=</span> <span class="fu">exp</span>(pi[<span class="dv">2</span>]<span class="sc">/</span>tau)<span class="sc">/</span><span class="fu">sum</span>(<span class="fu">exp</span>(pi<span class="sc">/</span>tau))</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  pr_soft3 <span class="ot">=</span> <span class="fu">exp</span>(pi[<span class="dv">3</span>]<span class="sc">/</span>tau)<span class="sc">/</span><span class="fu">sum</span>(<span class="fu">exp</span>(pi<span class="sc">/</span>tau))</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>  pr_soft <span class="ot">=</span> <span class="fu">c</span>(pr_soft1,pr_soft2,pr_soft3)</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(pr_soft)</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a><span class="co">#Función para una tirada</span></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>tirada_softmax <span class="ot">&lt;-</span> <span class="cf">function</span>(lista5){</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>  alphas <span class="ot">&lt;-</span> lista5[[<span class="dv">1</span>]]</span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>  betas <span class="ot">&lt;-</span> lista5[[<span class="dv">2</span>]]</span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>  tethas <span class="ot">&lt;-</span> lista5[[<span class="dv">3</span>]]</span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>  pi <span class="ot">&lt;-</span> lista5[[<span class="dv">4</span>]]</span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a>  tau<span class="ot">=</span><span class="fl">0.1</span></span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a>  sample <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>,<span class="dv">1</span>,<span class="at">prob=</span><span class="fu">softmax</span>(tau,pi))</span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a>  juego <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(<span class="dv">1</span>, <span class="dv">1</span>, tethas[sample])</span>
<span id="cb12-21"><a href="#cb12-21" aria-hidden="true" tabindex="-1"></a>  alphas[sample] <span class="ot">&lt;-</span> alphas[sample] <span class="sc">+</span> juego</span>
<span id="cb12-22"><a href="#cb12-22" aria-hidden="true" tabindex="-1"></a>  betas[sample] <span class="ot">&lt;-</span> betas[sample] <span class="sc">+</span> <span class="dv">1</span> <span class="sc">-</span> juego</span>
<span id="cb12-23"><a href="#cb12-23" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb12-24"><a href="#cb12-24" aria-hidden="true" tabindex="-1"></a>  lista5_salida<span class="ot">&lt;-</span><span class="fu">list</span>(alphas, betas, tethas,pi, juego,  sample)</span>
<span id="cb12-25"><a href="#cb12-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(lista5_salida)</span>
<span id="cb12-26"><a href="#cb12-26" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Reiterando este método para simular las jugadas de un año se obtiene:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="informe_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="informe_files/figure-html/unnamed-chunk-17-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="informe_files/figure-html/unnamed-chunk-17-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Las ganancias totales en ese año resultan  194  unidades monetaris"</code></pre>
</div>
</div>
<p>Se observa que en el año simulado se utilizaron mayormente las máquinas tres y dos, es decir, las máquinas que presentan una mayor probabilidad de éxito. Por este motivo, vemos que los gráficos a posteriori que más se modificaron en comparación al prior son los de estas 2 máquinas, dichas distribuciones parecen concentrarse en su verdadero valor poblacional a medida que se juega una mayor cantidad de veces. Mientras que el último gráfico evidencia la evolución diaria de las ganancias a lo largo del año, obteniendo una ganancia total igual a 194 unidades monetarias.</p>
<p>Luego se repite este procedimiento para simular 1000 años jugados con esta estrategia y se analizan los resultados.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="informe_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "La ganancia media por año es 185.069 unidades monetarias"</code></pre>
</div>
</div>
<p>A traves de la simulación de los 1000 años, se observa la distribución de las ganancias, la cual presenta un comportamiento levemente asimétrico por izquierda donde el 95% de los valores son mayores a 157 unidades monetarias. La ganancia media anual resulta igual a 185 unidades monetarias.</p>
<p>El método utilizado no es bayesiano, ya que, la elección de la máquina a utilizar se basa en una probabilidad que es función de las tasas observadas de éxito, las cuales no tienen en cuenta la distribuciones a posteriori correspondientes a cada máquina.</p>
</section>
<section id="estrategia-6-upper-bound" class="level2">
<h2 class="anchored" data-anchor-id="estrategia-6-upper-bound"><em>Estrategia 6: Upper-bound</em></h2>
<p>En esta estrategia se selecciona la máquina que tenga el mayor extremo derecho de un intervalo de credibilidad (construido a partir de la distribución a posteriori de la probabilidad de éxito).</p>
<p>Se presenta la función que simula esta estrategia para un día. Para esto se calculan los intervalos de credibilidad para las 3 distribuciones y se utiliza la máquina que presenta el mayor valor en el extremo derecho. Luego se simula el juego con la máquina elegida y se actualizan las distribuciones.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>upper_bound <span class="ot">&lt;-</span> <span class="cf">function</span>(lista6){</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  tethas <span class="ot">&lt;-</span> lista6[[<span class="dv">1</span>]]</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  alphas <span class="ot">&lt;-</span> lista6[[<span class="dv">2</span>]]</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  betas <span class="ot">&lt;-</span> lista6[[<span class="dv">3</span>]]</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>  UCB <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">qbeta</span>(<span class="fl">0.95</span>, alphas[<span class="dv">1</span>], betas[<span class="dv">1</span>]), </span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>           <span class="fu">qbeta</span>(<span class="fl">0.95</span>, alphas[<span class="dv">2</span>], betas[<span class="dv">2</span>]), </span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>           <span class="fu">qbeta</span>(<span class="fl">0.95</span>, alphas[<span class="dv">3</span>], betas[<span class="dv">3</span>]))</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>  sample <span class="ot">&lt;-</span> <span class="fu">order</span>(UCB <span class="sc">+</span> <span class="fu">runif</span>(<span class="dv">3</span>, <span class="fl">0.001</span>, <span class="fl">0.009</span>), <span class="at">decreasing =</span> <span class="cn">TRUE</span>)[<span class="dv">1</span>]</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>  juego <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(<span class="dv">1</span>, <span class="dv">1</span>, tethas[sample])</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>  alphas[sample] <span class="ot">&lt;-</span> alphas[sample] <span class="sc">+</span> juego</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>  betas[sample] <span class="ot">&lt;-</span> betas[sample] <span class="sc">+</span> <span class="dv">1</span> <span class="sc">-</span> juego</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>  lista6_salida<span class="ot">&lt;-</span><span class="fu">list</span>(tethas, alphas, betas, UCB, juego, sample, cont_exitos, cont_tiradas)</span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(lista6_salida)</span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Reiterando este método para simular las jugadas de un año se obtiene:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="informe_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="informe_files/figure-html/unnamed-chunk-20-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="informe_files/figure-html/unnamed-chunk-20-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "La ganancia anual es igual a 206 unidades monetarias"</code></pre>
</div>
</div>
<p>Durante el año simulado se utilizó en mayor medida la máquina dos, la cual presenta una mayor probabilidad de éxito en una tirada. El gráfico a posteriori de las máquinas uno y tres se ven levemente modificadas, mientras que dicha distribución para la máquina dos presenta valores mucho más concentrados alrededor del verdadero valor del parámetro. Por último se registra la evolución diaria de las ganancias, obteniendo un total de 206 unidades monetarias.</p>
<p>Luego se repite este procedimiento para simular 1000 años jugados con esta estrategia y se analizan los resultados.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="informe_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "La ganancia media por año es 191.805 unidades monetarias"</code></pre>
</div>
</div>
<p>Mediante el gráfico de las ganancias anuales se observa una distribución unimodal, con una leve asimetría a la izquierda en los cuales la ganancia anual se encuentra entre 166 y 211 unidades monetarias un 90% de las veces. La ganancia anual mediana resulta igual a 193 unidades monetarias.</p>
<p>El método utilizado para la elección de la máquina es bayesiano, ya que, actualiza la probabilidad de elección para cada máquina a medida que realiza las jugadas. En este caso, la distribución a posteriori se verá modificada y del mismo modo se modificarán los extremos derechos del intervalo de credibilidad.</p>
</section>
<section id="estrategia-7-thompson-sampling" class="level2">
<h2 class="anchored" data-anchor-id="estrategia-7-thompson-sampling"><em>Estrategia 7: Thompson sampling</em></h2>
<p>Para realizar la selección, este metodo toma una muestra de la distribución a posteriori de las probabilidades de éxito de cada máquina y se elige la máquina correspondiente a la muestra más grande.</p>
<p>Se presenta la función que simula esta estrategia para un día. Para esto se obtienen 3 muestras aleatorias provenientes de las 3 distribuciones y se utiliza la máquina que presenta el mayor valor. Luego se simula el juego con la máquina elegida y se actualizan las distribuciones.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>thompson_sampling <span class="ot">&lt;-</span> <span class="cf">function</span>(lista7){</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  alphas <span class="ot">&lt;-</span> lista7[[<span class="dv">1</span>]]</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  betas <span class="ot">&lt;-</span> lista7[[<span class="dv">2</span>]]</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  tethas <span class="ot">&lt;-</span> lista7[[<span class="dv">3</span>]]</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  muestra<span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">rbeta</span>(<span class="dv">1</span>,alphas[<span class="dv">1</span>],betas[<span class="dv">1</span>]), </span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>               <span class="fu">rbeta</span>(<span class="dv">1</span>,alphas[<span class="dv">2</span>],betas[<span class="dv">2</span>]), </span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>               <span class="fu">rbeta</span>(<span class="dv">1</span>,alphas[<span class="dv">3</span>],betas[<span class="dv">3</span>]))</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>  <span class="co">#print(muestra)</span></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>  sample <span class="ot">&lt;-</span> <span class="fu">order</span>(muestra, <span class="at">decreasing =</span> <span class="cn">TRUE</span>)[<span class="dv">1</span>]</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>  juego <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(<span class="dv">1</span>, <span class="dv">1</span>, tethas[sample])</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>  alphas[sample] <span class="ot">&lt;-</span> alphas[sample] <span class="sc">+</span> juego</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>  betas[sample] <span class="ot">&lt;-</span> betas[sample] <span class="sc">+</span> <span class="dv">1</span> <span class="sc">-</span> juego</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>  lista7_salida<span class="ot">&lt;-</span><span class="fu">list</span>(alphas, betas, tethas,  muestra, juego,  sample)</span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(lista7_salida)</span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Reiterando este método para simular las jugadas de un año se obtiene:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="informe_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="informe_files/figure-html/unnamed-chunk-23-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="informe_files/figure-html/unnamed-chunk-23-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Las ganancias totales en ese año resultan  166  unidades monetarias"</code></pre>
</div>
</div>
<p>Se observa que a lo largo del año se utilizó mayormente las máquinas dos y tres. Las distribuciones a posteriori de las probabilidades de éxitos para estas máquinas se encuentran más concentradas en los valores reales de los parámetros, mientras que la distribución de la máquina 1 no difiere tanto de la distribución a priori, esto se debe a que fue la máquina menos utilizada. El tercer gráfico presenta la evolución de las ganancias con el pasar de los días, se puede observar que la ganancia total resulta igual a 166 unidades monetarias.</p>
<p>Luego se repite este procedimiento para simular 1000 años jugados con esta estrategia y se analizan los resultados.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="informe_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "La ganancia media por año es 188.155 unidades monetarias"</code></pre>
</div>
</div>
<p>Se grafica la distribución aproximada de la ganancia anual. En este se diferencian un comportamiento simetrico centrado en aproximadamente 190 unidades monetarias. La media de las ganancias anuales es 188.52 unidades monetarias.</p>
<p>El método utilizado es bayesiano, ya que, actualiza las distribuciones a posteriori en cada tirada, por lo que la muestra elegida provendrá de una distribución distinta. De esta manera la elección de la máquina estará influida por los resultados de las tiradas anteriores</p>
</section>
</section>
<section id="conclusiones" class="level1">
<h1>Conclusiones</h1>
<p>Una vez simuladas todas las técnicas se procede a comparar los resultados obtenidos, y así poder recomendar a los futuros jugadores cuál de estas utilizar para maximizar las ganancias. Vale aclarar que se busca la estrategia que más se asemeje al caso ideal presentado al inicio del informe. Se presenta una tabla comparando algunas estadísticas</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: black !important; background-color: lightblue !important;">Estrategia</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: black !important; background-color: lightblue !important;">Media</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: black !important; background-color: lightblue !important;">Desvio</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: black !important; background-color: lightblue !important;">Mediana</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: black !important; background-color: lightblue !important;">Quantil 95</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">0. Caso ideal</td>
<td style="text-align: right;">200.64</td>
<td style="text-align: right;">9.59</td>
<td style="text-align: right;">201</td>
<td style="text-align: right;">216</td>
</tr>
<tr class="even">
<td style="text-align: left;">1. Completamente al azar</td>
<td style="text-align: right;">159.33</td>
<td style="text-align: right;">9.46</td>
<td style="text-align: right;">159</td>
<td style="text-align: right;">174</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2. Greedy con tasa observada</td>
<td style="text-align: right;">185.58</td>
<td style="text-align: right;">23.57</td>
<td style="text-align: right;">193</td>
<td style="text-align: right;">213</td>
</tr>
<tr class="even">
<td style="text-align: left;">3. Greedy con probabilidad a posteriori</td>
<td style="text-align: right;">189.18</td>
<td style="text-align: right;">18.81</td>
<td style="text-align: right;">193</td>
<td style="text-align: right;">213</td>
</tr>
<tr class="odd">
<td style="text-align: left;">4. e-Greedy</td>
<td style="text-align: right;">158.74</td>
<td style="text-align: right;">9.21</td>
<td style="text-align: right;">159</td>
<td style="text-align: right;">174</td>
</tr>
<tr class="even">
<td style="text-align: left;">5. Softmax</td>
<td style="text-align: right;">185.07</td>
<td style="text-align: right;">15.83</td>
<td style="text-align: right;">187</td>
<td style="text-align: right;">208</td>
</tr>
<tr class="odd">
<td style="text-align: left;">6. Upper-bound</td>
<td style="text-align: right;">191.80</td>
<td style="text-align: right;">13.56</td>
<td style="text-align: right;">193</td>
<td style="text-align: right;">212</td>
</tr>
<tr class="even">
<td style="text-align: left;">7. Thompson Sampling</td>
<td style="text-align: right;">188.16</td>
<td style="text-align: right;">11.92</td>
<td style="text-align: right;">189</td>
<td style="text-align: right;">206</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>Notoramiente las estrategias <em>completamente al azar</em> y <span class="math inline">\(\epsilon-\)</span><em>Greedy</em> presentan peores desempeños que el resto. Además, las medianas y cuantiles del resto de las estrategias se asemejan al caso ideal. Para tomar una decisión final, se acude a la comparación de distribuciones de ganancias anuales aproximadas que se presentaron a lo largo del informe.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="informe_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Ahora si, visto y considerando que lo deseado es asemejarse al comportamiento distribucional de las ganancias anuales en el <em>caso ideal</em>, se podrían recomendar las estrategias <em>upper-bound</em> y <em>thompson sampling</em> como las más rentables.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>